"""character_memory, a modular memory system for role-play characters.

Public surface:

* `CharacterMemoryConfig` / sub-configs — configure models, toggles, decay.
* `CharacterAgent` - the orchestrator (recall -> prompt -> LLM -> learn).
* Memory classes, the RAG system, chunkers, and the LLM/embedding abstractions
  are all re-exported for direct use or subclassing.
"""

from .agent import CharacterAgent
from .character import Character, ContextSnapshot, MemoryRecallSnapshot
from .chat import Chat
from .chunking import (
    Chunk,
    Chunker,
    get_chunker,
    register_chunker,
)
from .config import (
    CharacterMemoryConfig,
    ChunkingConfig,
    ContradictionPolicy,
    DedupConfig,
    EmbeddingConfig,
    KnowledgeGraphConfig,
    KnowledgeGraphPrivacy,
    LLMConfig,
    MemoryConfig,
    TemporalLLMConfig,
    TemporalResolutionConfig,
    WorldConfig,
    CalendarConfig,
)
from .emotion_vectors import emotion_similarity, emotion_vector, emotional_impact
from .llm import (
    EmbeddingProvider,
    LLMClient,
    OpenAICompatibleEmbeddings,
    OpenAICompatibleLLM,
)
from .llm.base import LLMResponse
from .memory import (
    CharacterInfoMemory,
    ConversationEventMemory,
    DialogueStyleMemory,
    DedupReport,
    Deduplicator,
    EmotionStatus,
    EpisodicMemory,
    ExtractionContext,
    ExtractionSpec,
    Extractor,
    HeartbeatJournal,
    KnowledgeGraphMemory,
    Memory,
    MemoryItem,
    RecallResult,
    MemoryScope,
    SQLiteStore,
    StructuredMemory,
    UserDirectiveMemory,
    UserFactMemory,
    UserSummaryMemory,
    WorldCommand,
    WorldEvent,
    WorldMemory,
    WorldRecordMemory,
    WorldSimulator,
    RuleBasedWorldSimulator,
    WorldSnapshot,
    WorldStateStore,
    CalendarEvent,
    CalendarOccurrence,
    CalendarSource,
    WorldRoutineCalendarSource,
    CalendarMemory,
    SELF_OWNER,
)
from .knowledge_graph import (
    GraphSourceProjector,
    KnowledgeGraphRetriever,
    KnowledgeGraphRetrivier,
    ProjectionResult,
    get_graph_source_projector,
    register_graph_source_projector,
)
from .manifest import MEMORY_NAMES, CharacterManifest
from .prompts import PromptConfig
from .rag import Hit, HybridSearch, RAGSystem
from .temporal import (
    DateParserTemporalResolutionEngine,
    LLMTemporalResolutionEngine,
    TemporalMatch,
    TemporalRange,
    TemporalResolution,
    TemporalResolutionEngine,
    get_temporal_resolution_engine,
    register_temporal_resolution_engine,
)
from .tools import (
    TextChunk,
    Tool,
    ToolCall,
    ToolCallEvent,
    ToolDefinition,
    ToolOutput,
    ToolRegistry,
    ToolResult,
    ToolResultEvent,
    TurnEffect,
    CalculateTimeDifference,
    GetConversationEvents,
    GetEventNeighbors,
    ResolveTimeRange,
    SearchConversationEvents,
    conversation_event_tools,
    GetKnowledgeGraphNeighbors,
    GetKnowledgeGraphNodes,
    SearchKnowledgeGraph,
    knowledge_graph_tools,
    get_tool,
    global_registry,
    memory_tools,
    world_tools,
    calendar_tools,
    GetWorldState,
    SearchWorld,
    WorldAction,
    SearchCalendarEvents,
    CreateCalendarEvent,
    UpdateCalendarEvent,
    EditCalendarEvent,
    CancelCalendarEvent,
    parse_time,
    register_tool,
    tool,
)

__version__ = "0.1.0"

__all__ = [
    "CharacterAgent",
    "Character",
    "ContextSnapshot",
    "MemoryRecallSnapshot",
    "Chat",
    "CharacterMemoryConfig",
    "LLMConfig",
    "EmbeddingConfig",
    "ChunkingConfig",
    "ContradictionPolicy",
    "KnowledgeGraphConfig",
    "KnowledgeGraphPrivacy",
    "MemoryConfig",
    "TemporalLLMConfig",
    "TemporalResolutionConfig",
    "WorldConfig",
    "CalendarConfig",
    "emotion_vector",
    "emotional_impact",
    "emotion_similarity",
    "DedupConfig",
    "PromptConfig",
    "CharacterManifest",
    "MEMORY_NAMES",
    "LLMClient",
    "LLMResponse",
    "EmbeddingProvider",
    "OpenAICompatibleLLM",
    "OpenAICompatibleEmbeddings",
    # Tool calling
    "Tool",
    "ToolCall",
    "ToolDefinition",
    "ToolOutput",
    "ToolResult",
    "ToolRegistry",
    "TurnEffect",
    "tool",
    "register_tool",
    "get_tool",
    "global_registry",
    "memory_tools",
    "world_tools",
    "calendar_tools",
    "GetWorldState",
    "SearchWorld",
    "WorldAction",
    "SearchCalendarEvents",
    "CreateCalendarEvent",
    "UpdateCalendarEvent",
    "EditCalendarEvent",
    "CancelCalendarEvent",
    "conversation_event_tools",
    "knowledge_graph_tools",
    "SearchConversationEvents",
    "GetConversationEvents",
    "GetEventNeighbors",
    "ResolveTimeRange",
    "CalculateTimeDifference",
    "SearchKnowledgeGraph",
    "GetKnowledgeGraphNodes",
    "GetKnowledgeGraphNeighbors",
    "parse_time",
    "TextChunk",
    "ToolCallEvent",
    "ToolResultEvent",
    "RAGSystem",
    "HybridSearch",
    "Hit",
    "TemporalMatch",
    "TemporalRange",
    "TemporalResolution",
    "TemporalResolutionEngine",
    "DateParserTemporalResolutionEngine",
    "LLMTemporalResolutionEngine",
    "get_temporal_resolution_engine",
    "register_temporal_resolution_engine",
    "Chunker",
    "Chunk",
    "get_chunker",
    "register_chunker",
    "Memory",
    "MemoryItem",
    "RecallResult",
    "MemoryScope",
    "ExtractionSpec",
    "StructuredMemory",
    "CharacterInfoMemory",
    "ConversationEventMemory",
    "DialogueStyleMemory",
    "UserFactMemory",
    "UserDirectiveMemory",
    "EpisodicMemory",
    "EmotionStatus",
    "HeartbeatJournal",
    "UserSummaryMemory",
    "KnowledgeGraphMemory",
    "KnowledgeGraphRetriever",
    "KnowledgeGraphRetrivier",
    "GraphSourceProjector",
    "ProjectionResult",
    "register_graph_source_projector",
    "get_graph_source_projector",
    "SQLiteStore",
    "Extractor",
    "ExtractionContext",
    "Deduplicator",
    "DedupReport",
    "WorldCommand",
    "WorldEvent",
    "WorldSnapshot",
    "WorldStateStore",
    "WorldRecordMemory",
    "WorldSimulator",
    "RuleBasedWorldSimulator",
    "WorldMemory",
    "CalendarEvent",
    "CalendarOccurrence",
    "CalendarSource",
    "WorldRoutineCalendarSource",
    "CalendarMemory",
    "SELF_OWNER",
]
